spring:
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
sharding:
  jdbc:
    datasource:
      names: ds_0
      ds_0:
        type: org.apache.commons.dbcp.BasicDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/demo?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: root
        password: hcp0113@@
    config:
      sharding:
        tables:
          t_order:
            actual-data-node: ds_0.t_order_${0..1}
            table-strategy:
              inline:
                sharding-column: order_id
                algorithm-expression: t_order_${order_id % 2}
            key-generator-column-name: order_id

